spring:
  datasource:
    url: jdbc:mysql://localhost:/test?characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
